// api/render.js (CommonJS)
const { GoogleGenAI } = require("@google/genai");

function stripDataUrlPrefix(b64) {
  const idx = b64.indexOf("base64,");
  return idx >= 0 ? b64.slice(idx + "base64,".length) : b64;
}

module.exports = async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST,OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.status(200).end();

  try {
    let body = req.body;
    if (typeof body === "string") body = JSON.parse(body);

    const { surveyData, planImageBase64 } = body;
    if (!planImageBase64) return res.status(400).json({ success: false, message: "Missing Plan Image" });

    const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_API_KEY });
    
    const style = surveyData?.materials || "Modern Residential";
    const stories = String(surveyData?.stories || "1").includes("2") ? "2-Story" : "1-Story";
    const garage = surveyData?.garage || "";
    const shape = surveyData?.shape || "Rectangular";

    const renderPrompt = `
Create a Photorealistic 3D EXTERIOR RENDER based on this blueprint.
Structure: ${stories} House, ${shape} footprint.
Style: ${style}. 
Garage: ${garage}.
View: Ground-level eye view from street. 
CRITICAL: DO NOT overlay the floor plan lines on the building. NO text in the image.
    `.trim();

    // UPDATED: Using gemini-3-pro-image-preview for best visuals
    const imgResp = await ai.models.generateContent({
      model: "gemini-3-pro-image-preview",
      contents: [
        { 
          role: "user", 
          parts: [
            { text: renderPrompt }, 
            { inlineData: { data: stripDataUrlPrefix(planImageBase64), mimeType: "image/png" } }
          ] 
        }
      ]
    });

    let imageBase64 = null;
    const parts = imgResp?.candidates?.[0]?.content?.parts || [];
    for (const p of parts) { 
        if (p.inlineData && p.inlineData.data) { 
            imageBase64 = p.inlineData.data; 
            break; 
        } 
    }

    if (!imageBase64) return res.status(500).json({ success: false, message: "No image generated by Gemini 3." });

    return res.status(200).json({ success: true, image: imageBase64 });
  } catch (err) {
    console.error("Render API Error:", err);
    return res.status(500).json({ success: false, message: err?.message });
  }
};